#ifndef THEGHOSTCROSSWORD_PARAMETERS_H
#define THEGHOSTCROSSWORD_PARAMETERS_H

#define NUM_THREADS 4
#define BOARD_SIZE 11
#define NUMBER_OF_TERMS 12
#define WORD_DISAPPEAR_TIME 60

#endif //THEGHOSTCROSSWORD_PARAMETERS_H
